# Generated by Django 3.1.13 on 2022-01-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('low_limit', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=100)),
                ('battery_size', models.IntegerField(default=0)),
                ('cost_or_shutoff', models.IntegerField(default=50)),
                ('hours_of_power', models.IntegerField(default=0)),
                ('longitude', models.FloatField(default=34.4208)),
                ('latitude', models.FloatField(default=-119.6982)),
                ('shutoff_risk', models.FloatField(default=0)),
                ('pred_solar_generation', models.TextField(blank=True, max_length=2048)),
                ('pred_opt_threshold', models.FloatField(default=0)),
                ('should_charge', models.BooleanField(default=True)),
                ('pred_good_time', models.TextField(blank=True, max_length=2048)),
                ('pred_best_schedule', models.TextField(blank=True, max_length=2048)),
                ('text', models.TextField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='user_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=254)),
                ('asset_name', models.CharField(blank=True, max_length=254)),
                ('type_of_asset', models.CharField(default='base', max_length=100)),
                ('declination', models.FloatField(blank=True, default=0)),
                ('azimuth', models.FloatField(blank=True, default=0)),
                ('modules_power', models.FloatField(blank=True, default=0)),
                ('start_charge_time', models.IntegerField(default=0)),
                ('end_charge_time', models.IntegerField(default=0)),
                ('demand', models.TextField(blank=True, max_length=2048)),
                ('duration', models.TextField(blank=True, max_length=2048)),
                ('text', models.TextField(blank=True, max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ucsb.user')),
            ],
        ),
        migrations.CreateModel(
            name='asset_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(default=0)),
                ('interval', models.IntegerField()),
                ('consumed_energy', models.FloatField()),
                ('produced_energy', models.FloatField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ucsb.user_asset')),
            ],
        ),
    ]
