# Generated by Django 3.1.13 on 2021-12-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=254)),
                ('asset_name', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ucsb.user')),
            ],
        ),
        migrations.CreateModel(
            name='asset_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('interval', models.IntegerField()),
                ('consumed_energy', models.FloatField()),
                ('produced_energy', models.FloatField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ucsb.user_asset')),
            ],
        ),
    ]
