# Generated by Django 3.1.13 on 2021-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsb', '0002_auto_20211217_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_data',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='asset_data',
            name='start_time',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
