# Generated by Django 3.1.13 on 2021-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsb', '0003_auto_20211218_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_data',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
