# Generated by Django 3.1.13 on 2021-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ag_user',
            fields=[
                ('user_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
