# Generated by Django 3.1.13 on 2021-12-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ag_user_asset_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ag_user_asset',
            name='user',
        ),
        migrations.DeleteModel(
            name='ag_asset_data',
        ),
        migrations.DeleteModel(
            name='ag_user',
        ),
        migrations.DeleteModel(
            name='ag_user_asset',
        ),
    ]
