name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f local.yml build
      run: docker-compose -f local.yml up

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: docker-compose -f local.yml run --rm django pytest

